apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-3
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/k3dvol-2"
