apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      containers:
      - name: nginx
        #image: nginx:latest
        env:
        - name: CUSTOM_ENV1_VARIABLE
          value: Value defined by Kustomize
