apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: env1
namePrefix: env1-
resources:
- namespace.yaml
- ../../base
patches:
- path: env1.yaml

#Original kustomization.yaml file after namePrefix
#bases:
#- ../../base

#patchesStrategicMerge:
#- env1.yaml

#resources:
#- namespace.yaml 