apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: env1
namePrefix: env1-
bases:
- ../../base

commonLabels:
  app: nginx-kustomize-env1

patchesStrategicMerge:
- env1.yaml

resources:
- namespace.yaml 
