apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: k3d-no-traefik
servers: 1 
agents: 2
options:
  # k3d:
  #   disabledLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --disable=traefik@server:0
        nodeFilters:
          - server:*