apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: env2
namePrefix: env2-

bases:
- ../../base

commonLabels:
  app: nginx-kustomize-env2

patchesStrategicMerge:
- env2.yaml

images:
- name: nginx 
  newTag: 1.23.1

resources:
- namespace.yaml