apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: my-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: my-nginx
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 80
