apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-kustomize-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-kustomize-base
  template:
    metadata:
      labels:
        app: nginx-kustomize-base
    spec:
      containers:
      - name: nginx
        image: nginx:1.22.1
        ports:
        - containerPort: 80
