apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: my-service
spec:
  selector:
    app: nginx-kustomize
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
