apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
  labels:
    course: zarf-101
    module: k8s-objects
    topic: configMaps
spec:
  containers:
  - name: nginx-cm
    image: nginx:1.23.1
    ports:
    - containerPort: 8088
